/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQueryRouteImport } from './routes/_app.query'
import { Route as AppEntitiesRouteImport } from './routes/_app.entities'
import { Route as AppDocumentsRouteImport } from './routes/_app.documents'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppAdminRouteImport } from './routes/_app.admin'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQueryRoute = AppQueryRouteImport.update({
  id: '/query',
  path: '/query',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRoute = AppEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/cases': typeof AppCasesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/entities': typeof AppEntitiesRoute
  '/query': typeof AppQueryRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AppAdminRoute
  '/cases': typeof AppCasesRoute
  '/dashboard': typeof AppDashboardRoute
  '/documents': typeof AppDocumentsRoute
  '/entities': typeof AppEntitiesRoute
  '/query': typeof AppQueryRoute
  '/settings': typeof AppSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/admin': typeof AppAdminRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documents': typeof AppDocumentsRoute
  '/_app/entities': typeof AppEntitiesRoute
  '/_app/query': typeof AppQueryRoute
  '/_app/settings': typeof AppSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cases'
    | '/dashboard'
    | '/documents'
    | '/entities'
    | '/query'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cases'
    | '/dashboard'
    | '/documents'
    | '/entities'
    | '/query'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/admin'
    | '/_app/cases'
    | '/_app/dashboard'
    | '/_app/documents'
    | '/_app/entities'
    | '/_app/query'
    | '/_app/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/query': {
      id: '/_app/query'
      path: '/query'
      fullPath: '/query'
      preLoaderRoute: typeof AppQueryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities': {
      id: '/_app/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AppEntitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCasesRoute: typeof AppCasesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEntitiesRoute: typeof AppEntitiesRoute
  AppQueryRoute: typeof AppQueryRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCasesRoute: AppCasesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEntitiesRoute: AppEntitiesRoute,
  AppQueryRoute: AppQueryRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
